---
- hosts: masters
  become: yes
  vars_prompt:
    - name: "domain_name"
      prompt: "Enter your base domain (e.g., subdomain.domain.in)"
      private: no
  tasks:
    - name: Add Rancher Helm repo
      kubernetes.core.helm_repository:
        name: rancher-stable
        repo_url: "https://releases.rancher.com/server-charts/stable"

    - name: Install Rancher
      kubernetes.core.helm:
        name: rancher
        chart_ref: rancher-stable/rancher
        release_namespace: cattle-system
        create_namespace: yes
        values: "{{ lookup('template', 'templates/rancher-values.yaml.j2') | from_yaml }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml
