---
- hosts: masters
  become: yes
  vars_prompt:
    - name: "cloudflare_api_token"
      prompt: "Enter your Cloudflare API Token"
      private: yes
    - name: "cloudflare_email"
      prompt: "Enter your email for Let's Encrypt"
      private: no
  tasks:
    - name: Add Jetstack Helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: yes
        values:
          installCRDs: true
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Create Cloudflare API token secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudflare-api-token-secret
            namespace: cert-manager
          stringData:
            api-token: "{{ cloudflare_api_token }}"
        kubeconfig: /etc/rancher/k3s/k3s.yaml

    - name: Apply ClusterIssuer
      kubernetes.core.k8s:
        state: present
        template: templates/cluster-issuer.yaml.j2
        kubeconfig: /etc/rancher/k3s/k3s.yaml